language: go

go:
  - 1.8.x
  - 1.9.x
  - master

go_import_path: github.com/Vehsamrak/telegramud

install:
  - go get ./internal/...
  - go get github.com/stretchr/testify

script:
  - go test -v ./tests/...
