env:
  DOCKER_COMPOSE_VERSION: 1.8.0

install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

script:
  - docker-compose run --no-deps application go test -v ./tests/...

deploy:
  - bash -c "DOCKER_HOST=${DEPLOY_SSH_HOST}:${DEPLOY_DOCKER_PORT} docker-compose up -d --build"
