language: go

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

before_script:
  # SSH key prepare
  - mv infrastructure/deploy.key.gpg .
  - gpg --yes --batch --passphrase=${DEPLOY_KEY_PASSWORD} deploy.key.gpg
  - chmod 600 deploy.key
  - mv deploy.key ~/.ssh
  - ssh-keyscan ${DEPLOY_SSH_HOST} >> ~/.ssh/known_hosts
  - echo "Host deploy" >> ~/.ssh/config
  - echo "  HostName ${DEPLOY_SSH_HOST}" >> ~/.ssh/config
  - echo "  User ${DEPLOY_SSH_USER}" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/deploy.key" >> ~/.ssh/config

script:
  # Running tests
  - docker-compose run --no-deps application go test -v ./tests/...

  # Login to docker hub
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}

  # Pushing images to docker hub
  - docker tag telegramud-application:1.0 ${DOCKERHUB_USERNAME}/telegramud-application:production
  - docker push ${DOCKERHUB_USERNAME}/telegramud-application:production
  - docker tag telegramud-database:1.0 ${DOCKERHUB_USERNAME}/telegramud-database:production
  - docker push ${DOCKERHUB_USERNAME}/telegramud-database:production

  # Deploy with docker compose only for branch master
  - export DOCKER_HOST=${DEPLOY_SSH_HOST}:${DEPLOY_DOCKER_PORT}
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker-compose up -d --build; else echo "skipped"; fi
