version: '2'

services:
  application:
    container_name: telegramud_application
    build: .
    image: telegramud-application:1.0
    environment:
      - TELEGRAM_APPLICATION_MUD_TOKEN
    command: env

  database:
    container_name: telegramud_database
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile-database
    image: telegramud-database:1.0
    ports:
      - "5433:5432"

volumes:
  database-data:
