version: '2'

services:
  application:
    container_name: telegramud_application
    build: .
    image: telegramud-application:1.0
    volumes:
      - .:/go/src/github.com/Vehsamrak/telegramud
    environment:
      - TELEGRAM_APPLICATION_MUD_TOKEN
    command: go run /go/src/github.com/Vehsamrak/telegramud/game.go

  database:
    container_name: telegramud_database
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile-database
    image: telegramud-database:1.0
    ports:
      - "5433:5432"

volumes:
  database-data:
