version: '2'

services:
  application:
    container_name: telegramud_application
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    image: telegramud-application:1.0
    environment:
      - TELEGRAM_APPLICATION_MUD_TOKEN
    volumes:
      - .:/go/src/github.com/vehsamrak/telegramud
    command: /go/src/github.com/vehsamrak/telegramud/infrastructure/entrypoint.sh

  database:
    container_name: telegramud_database
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile-database
    image: telegramud-database:1.0
    ports:
      - "5433:5432"

volumes:
  database-data:
