version: '2'

services:
  application:
    container_name: telegramud_application
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    image: telegramud-application:1.0
    environment:
      - TELEGRAM_APPLICATION_MUD_TOKEN
    command: go run game.go

  database:
    container_name: telegramud_database
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile-database
    image: telegramud-database:1.0
    ports:
      - "5433:5432"

  migrator:
    container_name: telegramud_migrator
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile-migrator
    image: telegramud-migrator:1.0
    volumes:
      - ./infrastructure/migrations:/project
    command: /project/migrator-entrypoint.sh

volumes:
  database-data:
