FROM ubuntu:16.04

RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/elwinar/rambler/releases/download/4.0.0/rambler-linux-amd64
RUN chmod +x rambler-linux-amd64
RUN mv rambler-linux-amd64 migrate

COPY ./infrastructure/migrations/rambler.json /
